version: '3.7'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    restart: unless-stopped

  image:
    build: 
      context: ./image
      dockerfile: Dockerfile.prod
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mailing:
    build: 
      context: ./mailing
      dockerfile: Dockerfile.prod
    expose:
      - "5050"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  postgres_data_prod:
  certbot-etc:
  certbot-var: