FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm install 
COPY --from=builder /app/dist ./dist
ENV NODE_ENV production
EXPOSE 3001
CMD ["npm", "start"]